name: Build and Deploy React App to Azure

on:
  push:
    branches:
      - main  # Gałąź, z której chcesz wdrażać

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build
        
      - name: List output files
        run: ls -l build

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bobrgram'  # Nazwa aplikacji webowej na Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Sekret przechowywany w GitHub Secrets
          package: './build'  # Ścieżka do folderu wyjściowego aplikacji React